api_platform:
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/merge-patch+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        # Change the default (30) items per page to 10
        pagination_items_per_page: 10
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
